PANDAS

In [5]:
import pandas as pd

path = ("/content/Salaries.csv")

df = pd.read_csv(path, header=0, index_col=3)
print(df)

           yearID teamID lgID    salary
playerID
barkele01    1985    ATL   NL    870000
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25575 rows x 4 columns]

In [6]:
selected_df = df[(df['salary']>1000000) & ((df['teamID'] == "HOU") | (df['teamID'] == "ATL"))]

In [7]:
selected_df

           yearID teamID lgID   salary
playerID
hornebo01    1985    ATL   NL  1500000
murphda05    1985    ATL   NL  1625000
suttebr01    1985    ATL   NL  1354167
ryanno01     1985    HOU   NL  1350000
hornebo01    1986    ATL   NL  1800000
...           ...    ...  ...      ...
quallch01    2015    HOU   AL  3000000
rasmuco01    2015    HOU   AL  8000000
singljo02    2015    HOU   AL  2000000
sippto01     2015    HOU   AL  2400000
valbulu01    2015    HOU   AL  4200000

[595 rows x 4 columns]

In [8]:
atl_df = df[(df['teamID'] == "ATL")]
atl_df

           yearID teamID lgID   salary
playerID
barkele01    1985    ATL   NL   870000
bedrost01    1985    ATL   NL   550000
benedbr01    1985    ATL   NL   545000
campri01     1985    ATL   NL   633333
ceronri01    1985    ATL   NL   625000
...           ...    ...  ...      ...
simmoan01    2015    ATL   NL  3000000
teherju01    2015    ATL   NL  1000000
terdojo01    2015    ATL   NL   507500
woodal02     2015    ATL   NL   520000
younger03    2015    ATL   NL  1000000

[886 rows x 4 columns]

In [9]:
atl_df['salary'].describe()

count    8.860000e+02
mean     2.206239e+06
std      3.432673e+06
min      6.000000e+04
25%      3.000000e+05
50%      6.000000e+05
75%      2.390625e+06
max      1.606180e+07
Name: salary, dtype: float64

In [33]:
df_dict = {
    "yearID" :[],
    "teamID" :[],
    "lgID" :[],
    "salary" :[]
}

In [34]:
for index, row in df.iterrows():
  for column in df.columns:
    df_dict[column].append(row[column])

In [35]:
created_df = pd.DataFrame(data=df_dict)

In [36]:
created_df

       yearID teamID lgID    salary
0        1985    ATL   NL    870000
1        1985    ATL   NL    550000
2        1985    ATL   NL    545000
3        1985    ATL   NL    633333
4        1985    ATL   NL    625000
...       ...    ...  ...       ...
25570    2015    WAS   NL    512800
25571    2015    WAS   NL    507500
25572    2015    WAS   NL  21000000
25573    2015    WAS   NL  16500000
25574    2015    WAS   NL  14000000

[25575 rows x 4 columns]

In [38]:
print(created_df.columns)

Index(['yearID', 'teamID', 'lgID', 'salary'], dtype='object')

In [39]:
new_columns = ["a", "b", "c", "d"]
created_df.columns = new_columns

print(created_df.columns)

Index(['a', 'b', 'c', 'd'], dtype='object')

In [40]:
created_df

          a    b   c         d
0      1985  ATL  NL    870000
1      1985  ATL  NL    550000
2      1985  ATL  NL    545000
3      1985  ATL  NL    633333
4      1985  ATL  NL    625000
...     ...  ...  ..       ...
25570  2015  WAS  NL    512800
25571  2015  WAS  NL    507500
25572  2015  WAS  NL  21000000
25573  2015  WAS  NL  16500000
25574  2015  WAS  NL  14000000

[25575 rows x 4 columns]

NUMPY

In [41]:
import numpy as np

In [42]:
numpy_list = [[1,2,3],
              [4,5,6],
              [7,8,9]]

In [43]:
numpy_array = np.array(numpy_list)

In [44]:
print(numpy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [47]:
print("Number of dimensions:", numpy_array.ndim)
print("Shape of the array:", numpy_array.shape)
print("Total number of elements:", numpy_array.size)
print("Data type of the elements:", numpy_array.dtype)
print("Size of each element in bytes:", numpy_array.itemsize)

Number of dimensions: 2
Shape of the array: (3, 3)
Total number of elements: 9
Data type of the elements: int64
Size of each element in bytes: 8

In [51]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaped_arr = arr.reshape(2,2,3)
print(reshaped_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

In [52]:
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

In [53]:
arr = np.array([-4, -3, -2, -1, 1, 2, 3, 4, 5])
arr1 = np.array([-9, -8, -7, -6, -5, 5, 6, 7, 8])

In [60]:
print(arr.argmin())
print(arr.argmax())
print(arr.min())
print(arr.max())
print(arr.mean())
print(arr.sum())
print(arr.std())
print(np.dot(arr,arr1))
print(np.square(arr))
print(np.sqrt(arr1))
print(np.abs(arr))
print(np.sign(arr))
print(np.mod(arr,2))

0
8
-4
5
0.5555555555555556
5
3.02254900194121
171
[16  9  4  1  1  4  9 16 25]
[       nan        nan        nan        nan        nan 2.23606798
 2.44948974 2.64575131 2.82842712]
[4 3 2 1 1 2 3 4 5]
[-1 -1 -1 -1  1  1  1  1  1]
[0 1 0 1 1 0 1 0 1]

<ipython-input-60-5dd82b0ede14>:10: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr1))

In [63]:
genarr = np.arange(1,11,3)
genarr

array([ 1,  4,  7, 10])

In [65]:
onesarr = np.ones((3,3), dtype = int)
onesarr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [67]:
zerosarr = np.zeros((3,3))
zerosarr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
eyearr = np.eye(3,4, dtype = int)
eyearr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [71]:
linarr = np.linspace(1,2,3)
linarr

array([1. , 1.5, 2. ])

SCIKIT-LEARN